# fly.toml app configuration file generated for phoenix-vault-dry-morning-3006 on 2024-07-19T16:42:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phoenix-vault-dry-morning-3006'
primary_region = 'sea'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'phoenix-vault-dry-morning-3006.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
    source = "phoenix_vault_data"
    destination = "/data"
    